ws_user:
    resource: "@WSBundle/Resources/config/routing/user.yml"
    prefix:   /user

ws_project:
    resource: "@WSBundle/Resources/config/routing/project.yml"
    prefix:   /project

ws_comment:
    resource: "@WSBundle/Resources/config/routing/comment.yml"
    prefix:   /comment

ws_follow:
    resource: "@WSBundle/Resources/config/routing/follow.yml"
    prefix:   /follow

ws_group:
    resource: "@WSBundle/Resources/config/routing/collaborationGroup.yml"
    prefix:   /collaborationGroup

ws_membership:
    resource: "@WSBundle/Resources/config/routing/membership.yml"
    prefix:   /membership

