collaborationGroup_new:
    path:     /new
    defaults: { _controller: "WSBundle:CollaborationGroup:new" }
    methods:  [GET, POST]

collaborationGroup_updateName:
    path:     /updateName
    defaults: { _controller: "WSBundle:CollaborationGroup:updateName" }
    methods:  [GET, POST]

collaborationGroup_getByAdminUser:
    path:     /getByAdminUser
    defaults: { _controller: "WSBundle:CollaborationGroup:getByAdminUser" }
    methods:  [POST]

collaborationGroup_getByUser:
    path:     /getByUser
    defaults: { _controller: "WSBundle:CollaborationGroup:getByUser" }
    methods:  [POST]