membership_addMember:
    path:     /addMember
    defaults: { _controller: "WSBundle:Membership:addMember" }
    methods:  [GET, POST]

membership_deleteMember:
    path:     /deleteMember
    defaults: { _controller: "WSBundle:Membership:deleteMember" }
    methods:  [GET, POST]

membership_getByGroupNameMember:
    path:     /getByGroupName
    defaults: { _controller: "WSBundle:Membership:getByGroupName" }
    methods:  [GET, POST]