project_getAll:
    path:     /getAll
    defaults: { _controller: "WSBundle:Project:getAll" }
    methods:  [GET, POST]

project_getById:
    path:     /getById
    defaults: { _controller: "WSBundle:Project:getById" }
    methods:  [GET, POST]

project_getByName:
    path:     /getByName
    defaults: { _controller: "WSBundle:Project:getByName" }
    methods:  [GET, POST]

project_create:
    path:     /create
    defaults: { _controller: "WSBundle:Project:create" }
    methods:  [GET, POST]

project_getMembers:
    path:     /getMembers
    defaults: { _controller: "WSBundle:Project:getMembersByGroupName" }
    methods:  [GET, POST]

project_getContributionsByProject:
    path:     /getContributionsByProject
    defaults: { _controller: "WSBundle:Project:getContributionsByProject" }
    methods:  [GET, POST]


