user_new:
    path:     /new
    defaults: { _controller: "WSBundle:User:new" }
    methods:  [GET, POST]

user_update:
    path:     /update
    defaults: { _controller: "WSBundle:User:update" }
    methods:  [GET, POST]

user_delete:
    path:     /delete
    defaults: { _controller: "WSBundle:User:delete" }
    methods:  [GET, POST]

user_getByEmail:
    path:     /getByEmail
    defaults: { _controller: "WSBundle:User:getByEmail" }
    methods:  [GET, POST]

user_getCount:
    path:     /getProjectsCount
    defaults: { _controller: "WSBundle:User:getByEmailWithCount" }
    methods:  [GET, POST]

user_udateToken:
    path:     /updateToken
    defaults: { _controller: "WSBundle:User:updateToken" }
    methods:  [GET, POST]

user_login:
    path:     /login
    defaults: { _controller: "WSBundle:User:login" }
    methods:  [GET, POST]

